server:
  port: 8080
  contextPath: /

---
#数据库相关配置
spring :
  datasource :
    username : excel
    password : 123456
    url: jdbc:mysql://60.205.223.33:60006/excel?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    driverClassName : com.mysql.jdbc.Driver

---

#jpa相关配置
spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
